// Code generated for go_workspace_example
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/delyke/go_workspace_example/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PartRepository is an autogenerated mock type for the PartRepository type
type PartRepository struct {
	mock.Mock
}

type PartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartRepository) EXPECT() *PartRepository_Expecter {
	return &PartRepository_Expecter{mock: &_m.Mock}
}

// CreatePart provides a mock function with given fields: ctx, part
func (_m *PartRepository) CreatePart(ctx context.Context, part *model.Part) error {
	ret := _m.Called(ctx, part)

	if len(ret) == 0 {
		panic("no return value specified for CreatePart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Part) error); ok {
		r0 = rf(ctx, part)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartRepository_CreatePart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePart'
type PartRepository_CreatePart_Call struct {
	*mock.Call
}

// CreatePart is a helper method to define mock.On call
//   - ctx context.Context
//   - part *model.Part
func (_e *PartRepository_Expecter) CreatePart(ctx interface{}, part interface{}) *PartRepository_CreatePart_Call {
	return &PartRepository_CreatePart_Call{Call: _e.mock.On("CreatePart", ctx, part)}
}

func (_c *PartRepository_CreatePart_Call) Run(run func(ctx context.Context, part *model.Part)) *PartRepository_CreatePart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Part))
	})
	return _c
}

func (_c *PartRepository_CreatePart_Call) Return(_a0 error) *PartRepository_CreatePart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartRepository_CreatePart_Call) RunAndReturn(run func(context.Context, *model.Part) error) *PartRepository_CreatePart_Call {
	_c.Call.Return(run)
	return _c
}

// GetPart provides a mock function with given fields: ctx, UUID
func (_m *PartRepository) GetPart(ctx context.Context, UUID string) (*model.Part, error) {
	ret := _m.Called(ctx, UUID)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Part, error)); ok {
		return rf(ctx, UUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Part); ok {
		r0 = rf(ctx, UUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, UUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartRepository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type PartRepository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - UUID string
func (_e *PartRepository_Expecter) GetPart(ctx interface{}, UUID interface{}) *PartRepository_GetPart_Call {
	return &PartRepository_GetPart_Call{Call: _e.mock.On("GetPart", ctx, UUID)}
}

func (_c *PartRepository_GetPart_Call) Run(run func(ctx context.Context, UUID string)) *PartRepository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PartRepository_GetPart_Call) Return(_a0 *model.Part, _a1 error) *PartRepository_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartRepository_GetPart_Call) RunAndReturn(run func(context.Context, string) (*model.Part, error)) *PartRepository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, filters
func (_m *PartRepository) ListParts(ctx context.Context, filters *model.PartsFilter) ([]*model.Part, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.PartsFilter) ([]*model.Part, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.PartsFilter) []*model.Part); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.PartsFilter) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartRepository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type PartRepository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *model.PartsFilter
func (_e *PartRepository_Expecter) ListParts(ctx interface{}, filters interface{}) *PartRepository_ListParts_Call {
	return &PartRepository_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filters)}
}

func (_c *PartRepository_ListParts_Call) Run(run func(ctx context.Context, filters *model.PartsFilter)) *PartRepository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.PartsFilter))
	})
	return _c
}

func (_c *PartRepository_ListParts_Call) Return(_a0 []*model.Part, _a1 error) *PartRepository_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartRepository_ListParts_Call) RunAndReturn(run func(context.Context, *model.PartsFilter) ([]*model.Part, error)) *PartRepository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartRepository creates a new instance of PartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartRepository {
	mock := &PartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
