// Code generated for go_workspace_example
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/delyke/go_workspace_example/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, uuid, status
func (_m *OrderRepository) Cancel(ctx context.Context, uuid string, status model.OrderStatus) error {
	ret := _m.Called(ctx, uuid, status)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.OrderStatus) error); ok {
		r0 = rf(ctx, uuid, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type OrderRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - status model.OrderStatus
func (_e *OrderRepository_Expecter) Cancel(ctx interface{}, uuid interface{}, status interface{}) *OrderRepository_Cancel_Call {
	return &OrderRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, uuid, status)}
}

func (_c *OrderRepository_Cancel_Call) Run(run func(ctx context.Context, uuid string, status model.OrderStatus)) *OrderRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.OrderStatus))
	})
	return _c
}

func (_c *OrderRepository_Cancel_Call) Return(_a0 error) *OrderRepository_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_Cancel_Call) RunAndReturn(run func(context.Context, string, model.OrderStatus) error) *OrderRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, order
func (_m *OrderRepository) Create(ctx context.Context, order *model.Order) (*model.Order, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) (*model.Order, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) *model.Order); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *OrderRepository_Expecter) Create(ctx interface{}, order interface{}) *OrderRepository_Create_Call {
	return &OrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *OrderRepository_Create_Call) Run(run func(ctx context.Context, order *model.Order)) *OrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Order))
	})
	return _c
}

func (_c *OrderRepository_Create_Call) Return(_a0 *model.Order, _a1 error) *OrderRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Order) (*model.Order, error)) *OrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, uuid
func (_m *OrderRepository) Get(ctx context.Context, uuid string) (*model.Order, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *OrderRepository_Expecter) Get(ctx interface{}, uuid interface{}) *OrderRepository_Get_Call {
	return &OrderRepository_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *OrderRepository_Get_Call) Run(run func(ctx context.Context, uuid string)) *OrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_Get_Call) Return(_a0 *model.Order, _a1 error) *OrderRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*model.Order, error)) *OrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Pay provides a mock function with given fields: ctx, uuid, method, txUUID, status
func (_m *OrderRepository) Pay(ctx context.Context, uuid string, method model.PaymentMethod, txUUID string, status model.OrderStatus) (*model.Order, error) {
	ret := _m.Called(ctx, uuid, method, txUUID, status)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.PaymentMethod, string, model.OrderStatus) (*model.Order, error)); ok {
		return rf(ctx, uuid, method, txUUID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.PaymentMethod, string, model.OrderStatus) *model.Order); ok {
		r0 = rf(ctx, uuid, method, txUUID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.PaymentMethod, string, model.OrderStatus) error); ok {
		r1 = rf(ctx, uuid, method, txUUID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type OrderRepository_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - method model.PaymentMethod
//   - txUUID string
//   - status model.OrderStatus
func (_e *OrderRepository_Expecter) Pay(ctx interface{}, uuid interface{}, method interface{}, txUUID interface{}, status interface{}) *OrderRepository_Pay_Call {
	return &OrderRepository_Pay_Call{Call: _e.mock.On("Pay", ctx, uuid, method, txUUID, status)}
}

func (_c *OrderRepository_Pay_Call) Run(run func(ctx context.Context, uuid string, method model.PaymentMethod, txUUID string, status model.OrderStatus)) *OrderRepository_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.PaymentMethod), args[3].(string), args[4].(model.OrderStatus))
	})
	return _c
}

func (_c *OrderRepository_Pay_Call) Return(_a0 *model.Order, _a1 error) *OrderRepository_Pay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_Pay_Call) RunAndReturn(run func(context.Context, string, model.PaymentMethod, string, model.OrderStatus) (*model.Order, error)) *OrderRepository_Pay_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
