// Code generated for go_workspace_example
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/delyke/go_workspace_example/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, orderID
func (_m *OrderService) Cancel(ctx context.Context, orderID string) error {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type OrderService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *OrderService_Expecter) Cancel(ctx interface{}, orderID interface{}) *OrderService_Cancel_Call {
	return &OrderService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, orderID)}
}

func (_c *OrderService_Cancel_Call) Run(run func(ctx context.Context, orderID string)) *OrderService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_Cancel_Call) Return(_a0 error) *OrderService_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_Cancel_Call) RunAndReturn(run func(context.Context, string) error) *OrderService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, userUUID, partUUIDs
func (_m *OrderService) Create(ctx context.Context, userUUID string, partUUIDs []string) (string, float64, error) {
	ret := _m.Called(ctx, userUUID, partUUIDs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 float64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (string, float64, error)); ok {
		return rf(ctx, userUUID, partUUIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) string); ok {
		r0 = rf(ctx, userUUID, partUUIDs)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) float64); ok {
		r1 = rf(ctx, userUUID, partUUIDs)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []string) error); ok {
		r2 = rf(ctx, userUUID, partUUIDs)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// OrderService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
//   - partUUIDs []string
func (_e *OrderService_Expecter) Create(ctx interface{}, userUUID interface{}, partUUIDs interface{}) *OrderService_Create_Call {
	return &OrderService_Create_Call{Call: _e.mock.On("Create", ctx, userUUID, partUUIDs)}
}

func (_c *OrderService_Create_Call) Run(run func(ctx context.Context, userUUID string, partUUIDs []string)) *OrderService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *OrderService_Create_Call) Return(_a0 string, _a1 float64, _a2 error) *OrderService_Create_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *OrderService_Create_Call) RunAndReturn(run func(context.Context, string, []string) (string, float64, error)) *OrderService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, orderUUID
func (_m *OrderService) Get(ctx context.Context, orderUUID string) (*model.Order, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *OrderService_Expecter) Get(ctx interface{}, orderUUID interface{}) *OrderService_Get_Call {
	return &OrderService_Get_Call{Call: _e.mock.On("Get", ctx, orderUUID)}
}

func (_c *OrderService_Get_Call) Run(run func(ctx context.Context, orderUUID string)) *OrderService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_Get_Call) Return(_a0 *model.Order, _a1 error) *OrderService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_Get_Call) RunAndReturn(run func(context.Context, string) (*model.Order, error)) *OrderService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Pay provides a mock function with given fields: ctx, orderUUID, paymentMethod
func (_m *OrderService) Pay(ctx context.Context, orderUUID string, paymentMethod model.PaymentMethod) (string, error) {
	ret := _m.Called(ctx, orderUUID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.PaymentMethod) (string, error)); ok {
		return rf(ctx, orderUUID, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.PaymentMethod) string); ok {
		r0 = rf(ctx, orderUUID, paymentMethod)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.PaymentMethod) error); ok {
		r1 = rf(ctx, orderUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type OrderService_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - paymentMethod model.PaymentMethod
func (_e *OrderService_Expecter) Pay(ctx interface{}, orderUUID interface{}, paymentMethod interface{}) *OrderService_Pay_Call {
	return &OrderService_Pay_Call{Call: _e.mock.On("Pay", ctx, orderUUID, paymentMethod)}
}

func (_c *OrderService_Pay_Call) Run(run func(ctx context.Context, orderUUID string, paymentMethod model.PaymentMethod)) *OrderService_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.PaymentMethod))
	})
	return _c
}

func (_c *OrderService_Pay_Call) Return(_a0 string, _a1 error) *OrderService_Pay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_Pay_Call) RunAndReturn(run func(context.Context, string, model.PaymentMethod) (string, error)) *OrderService_Pay_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
